### ISSUE TITLE
MAKE Errors

### ISSUE THREAD

**Issue by GabrielTK** [ivyl/rootkit#3]
Good Evening,
I'm getting some errors on Ubuntu 16.10 (on Vagrant):
`make -C /lib/modules/4.8.0-22-generic/build M=/home/vagrant/rk/rootkit-master modules
make[1]: Entering directory '/usr/src/linux-headers-4.8.0-22-generic'
  CC [M]  /home/vagrant/rk/rootkit-master/rt.o
/home/vagrant/rk/rootkit-master/rt.c: In function 'proc_readdir_new':
/home/vagrant/rk/rootkit-master/rt.c:96:41: error: passing argument 3 of 'proc_readdir_orig' from incompatible pointer type [-Werror=incompatible-pointer-types]
  return proc_readdir_orig(filp, dirent, proc_filldir_new);
                                         ^~~~~~~~~~~~~~~~
/home/vagrant/rk/rootkit-master/rt.c:96:41: note: expected 'filldir_t {aka int (*)(struct dir_context *, const char *, int,  long long int,  long long unsigned int,  unsigned int)}' but argument is of type 'int (*)(void *, const char *, int,  loff_t,  u64,  unsigned int) {aka int (*)(void *, const char *, int,  long long int,  long long unsigned int,  unsigned int)}'
/home/vagrant/rk/rootkit-master/rt.c: In function 'fs_readdir_new':
/home/vagrant/rk/rootkit-master/rt.c:108:39: error: passing argument 3 of 'fs_readdir_orig' from incompatible pointer type [-Werror=incompatible-pointer-types]
  return fs_readdir_orig(filp, dirent, fs_filldir_new);
                                       ^~~~~~~~~~~~~~
/home/vagrant/rk/rootkit-master/rt.c:108:39: note: expected 'filldir_t {aka int (*)(struct dir_context *, const char *, int,  long long int,  long long unsigned int,  unsigned int)}' but argument is of type 'int (*)(void *, const char *, int,  loff_t,  u64,  unsigned int) {aka int (*)(void *, const char *, int,  long long int,  long long unsigned int,  unsigned int)}'
/home/vagrant/rk/rootkit-master/rt.c: In function 'rtkit_write':
/home/vagrant/rk/rootkit-master/rt.c:148:40: error: incompatible types when assigning to type 'kuid_t {aka struct <anonymous>}' from type 'int'
   credentials->uid = credentials->euid = 0;
                                        ^
/home/vagrant/rk/rootkit-master/rt.c:149:40: error: incompatible types when assigning to type 'kgid_t {aka struct <anonymous>}' from type 'int'
   credentials->gid = credentials->egid = 0;
                                        ^
/home/vagrant/rk/rootkit-master/rt.c: In function 'procfs_clean':
/home/vagrant/rk/rootkit-master/rt.c:175:12: error: 'struct file_operations' has no member named 'readdir'; did you mean 'read'?
   proc_fops->readdir = proc_readdir_orig;
            ^~
/home/vagrant/rk/rootkit-master/rt.c: In function 'fs_clean':
/home/vagrant/rk/rootkit-master/rt.c:184:10: error: 'struct file_operations' has no member named 'readdir'; did you mean 'read'?
   fs_fops->readdir = fs_readdir_orig;
          ^~
/home/vagrant/rk/rootkit-master/rt.c: In function 'procfs_init':
/home/vagrant/rk/rootkit-master/rt.c:192:15: error: implicit declaration of function 'create_proc_entry' [-Werror=implicit-function-declaration]
  proc_rtkit = create_proc_entry("rtkit", 0666, NULL);
               ^~~~~~~~~~~~~~~~~
/home/vagrant/rk/rootkit-master/rt.c:192:13: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
  proc_rtkit = create_proc_entry("rtkit", 0666, NULL);
             ^
/home/vagrant/rk/rootkit-master/rt.c:194:24: error: dereferencing pointer to incomplete type 'struct proc_dir_entry'
  proc_root = proc_rtkit->parent;
                        ^~
/home/vagrant/rk/rootkit-master/rt.c:203:31: error: 'struct file_operations' has no member named 'readdir'; did you mean 'read'?
  proc_readdir_orig = proc_fops->readdir;
                               ^~
/home/vagrant/rk/rootkit-master/rt.c:205:11: error: 'struct file_operations' has no member named 'readdir'; did you mean 'read'?
  proc_fops->readdir = proc_readdir_new;
           ^~
/home/vagrant/rk/rootkit-master/rt.c: In function 'fs_init':
/home/vagrant/rk/rootkit-master/rt.c:222:27: error: 'struct file_operations' has no member named 'readdir'; did you mean 'read'?
  fs_readdir_orig = fs_fops->readdir;
                           ^~
/home/vagrant/rk/rootkit-master/rt.c:224:9: error: 'struct file_operations' has no member named 'readdir'; did you mean 'read'?
  fs_fops->readdir = fs_readdir_new;
         ^~
cc1: some warnings being treated as errors
scripts/Makefile.build:295: recipe for target '/home/vagrant/rk/rootkit-master/rt.o' failed
make[2]: *** [/home/vagrant/rk/rootkit-master/rt.o] Error 1
Makefile:1489: recipe for target '_module_/home/vagrant/rk/rootkit-master' failed
make[1]: *** [_module_/home/vagrant/rk/rootkit-master] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.8.0-22-generic'
Makefile:8: recipe for target 'default' failed
make: *** [default] Error 2
`
Thank you,
Gabriel

**Comment by huntergregal** [comment]
I am having the same issue

**Comment by MattHarris1996** [comment]
I believe that the issues you are having is due to the kernel version that is running on the new versions of Ubuntu. Maybe try and install an older version of ubuntu
